### ISSUE TITLE
リファレンスの一覧でクラスメソッドとインスタンスメソッドの区別がつきにくい

### ISSUE THREAD

**Issue by sho-h** [mirichi/dxruby-doc#1]
Spriteクラスのcheckメソッドやdrawメソッドのようにクラスメソッドもインスタンスメソッドも持っている場合に一覧で区別をするのが難しいようです。

* http://mirichi.github.io/dxruby-doc/api/Sprite.html

初学者の方が読むのに「.check」と「#check」にされないとかであれば . や # をつけたいところです。あるいはインスタンスメソッドとクラスメソッドの段を設けるかするとわかりやすいかもしれません。

**Comment by mirichi** [comment]
なるほど、確かに左の一覧ではわかりませんね。。。
気づきませんでした。
クラスメソッドとインスタンスメソッドがはっきりわかるような表示に変更したいと思いますけども、これ人に作ってもらったプログラムで生成してるんで、どう修正すればいいのかを調べてからになりますので、ちょいかかりますー

**Comment by sho-h** [comment]
検討ありがとうございます！急ぎませんので大丈夫です！

> されないとかであれば

ここはされないとかでなければ、としたかったのでした...書き間違えました。

**Comment by mirichi** [comment]
.と#を追加致しました。
ついでにInputモジュールのメソッドがインスタンスメソッドになってるバグを見つけたので直しておきました。
対応が遅くなってすみませんでした。
